name: Build project
on:
  push:
  pull_request:

jobs:
  build:
    env:
      RUST_LOG: debug
      # Deactivate incremental builds to speed up build times
      CARGO_INCREMENTAL: 0
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Update apt cache
        run: sudo apt update
      - name: Install system dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            curl git build-essential \
            libgtk-4-dev gettext libdbus-1-dev libssl-dev libudev-dev \
            libxml2-utils desktop-file-utils \
            python3-pip ninja-build
      - name: Install Meson
        run: |
          # Newer version needed for --interactive flag needed below
          python3 -m pip install --user -v 'meson==1.5.0'
      # Rust cache to speed up builds
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "credentialsd-common -> ../build/target\n
                      credentialsd -> ../build/target\n
                      credentialsd-ui -> ../build/target"
      - name: Setup meson project
        run: meson setup build
      - name: Build
        run: ninja -C build
      - name: Test
        # We have to use the --interactive flag because of some
        # weird issue with meson hanging after cargo exits due to the TestDBus.
        # Probably has to do with forking the test processes.
        run: meson test --interactive
        working-directory: build/
      - name: Check clippy recommendations (Common)
        run: env CARGO_HOME=build/cargo-home cargo clippy --manifest-path credentialsd-common/Cargo.toml --target-dir build/target/release --no-deps --release
      - name: Check clippy recommendations (UI)
        run: env CARGO_HOME=build/cargo-home cargo clippy --manifest-path credentialsd-ui/Cargo.toml --target-dir build/target/release --no-deps --release
      - name: Check clippy recommendations (Server)
        run: env CARGO_HOME=build/cargo-home cargo clippy --manifest-path credentialsd/Cargo.toml --target-dir build/target/release --no-deps --release
      - name: Check formatting (Common)
        run: cargo fmt --check
        working-directory: credentialsd-common
      - name: Check formatting (UI)
        run: cargo fmt --check
        working-directory: credentialsd-ui
      - name: Check formatting (Server)
        run: cargo fmt --check
        working-directory: credentialsd
